apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQ=
  Footer
  © 2022 GitHub, Inc.
  Footer navigation
  Terms
  Priv